### ISSUE TITLE
Add support for the new "speculative_exec" endpoint

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-ecosystem/casper-client-rs#25] opened 2022-04-25 14:30 UTC
https://github.com/casper-network/casper-node/issues/2880 downstream dependency

~The new method should be called `execute-deploy` and require the following arguments:~
~* optional block identifier (as per `get-block` subcommand)~
~* deploy_file (as per `send-deploy` subcommand)~

We should provide two new subcommands, `speculative-put-deploy` and `speculative-send-deploy`, mirroring `put-deploy` and `send-deploy`.  Both subcommands should take an optional block identifier (as per `get-block` subcommand) to be used to specify the global state root to be used.

Internally, they should construct a JSON-RPC request and call the node's `speculative_exec` endpoint.

**Comment by Fraser999** [comment] 2022-06-16 01:16
I'd actually prefer if we didn't add a new subcommand for this.  I think it would be better to provide a `--dry-run` argument to `put-deploy`, `send-deploy` and `transfer`.  The new arg would take an optional block identifier.

**Comment by goral09** [comment] 2022-06-16 08:22
I'm not sure about that last idea of just adding a flag to the already existing commands. That would be fine if the new endpoint lived on the same port as the previous commands but it will be a weird UX if you had to change the address when adding a command flag. 
 
 Example:
 ```
casper-client --node <node-address> put-deploy <args> 
```
but for `--dry-run`
```
casper-client --node <different-node-address> put-deploy --dry-run <args>
```

**Comment by Fraser999** [comment] 2022-06-16 21:45
Discussed in standup, and the consensus was to provide three new subcommands, similar to `put-deploy`, `send-deploy` and `transfer`, but which use the `speculative_exec` RPC.  They should be named to reflect the fact that they're calling through to `speculative_exec`.

Names were not discussed, so an initial suggestion is to add a `speculative-` prefix to each of the mirrored names.

**Comment by Fraser999** [comment] 2022-06-17 15:21
Discussed again, and we agreed to not implement `speculative-transfer`.

**Comment by RitaMAllenCA** [comment] 2023-04-14 21:39
closing as a duplicate of #57

**Closed by RitaMAllenCA** 2023-04-14 21:39 UTC
